[WIP] Change Omega2 RGB example to use sliders
cloud4rpi/cloud4rpi-omega2-python pull request #3
Opened 2018-07-17 14:16 UTC by Himura2la

2018-07-18 13:26 UTC, sky3d requested changes

2018-07-18 13:26 UTC, sky3d commented on README.md
>  ![](https://github.com/cloud4rpi/docs/raw/master/example-img/omega_led.png)
You need to change image for a slider.

2018-07-18 14:24 UTC, Himura2la commented on README.md
>  ![](https://github.com/cloud4rpi/docs/raw/master/example-img/omega_led.png)
The sliders appear later, it's an onboard LED

2018-07-18 17:26 UTC, Himura2la commented on README.md
>  ![](https://github.com/cloud4rpi/docs/raw/master/example-img/omega_led.png)
I added a sliders image

2018-07-20 09:52 UTC, sky3d approved these changes

2018-07-26 13:25 UTC, const314 approved these changes

2018-07-26 13:31 UTC, vutenkov commented
> All checks have failed

2018-07-26 13:42 UTC, Himura2la commented
That's because Python 3.3 does not have `enum` module. Sw need to replace 3.3 with 3.7

2018-07-26 13:44 UTC, vutenkov commented
> https://github.com/cloud4rpi/cloud4rpi-omega2-python/pull/4
> To fix the build: https://github.com/cloud4rpi/cloud4rpi-omega2-python/compare/tavis-python37

2018-07-26 13:49 UTC, Himura2la commented
This failure is unrelated to the PR itself, the probability of a real failure in 3.3 or 3.7 is very low.

2019-06-14 11:39 UTC, merged